version: '3'
services:
  wk-gdi-automate:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGEN_NAME}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      X_API_KEY: ${X_API_KEY}
      DSN: ${DSN}
      API_PORT: ${API_PORT}
    # ports:
    #   - 3000:3000
    restart: always
    network_mode: "host"
    dns: 172.16.1.4
    dns_search: fleni.org.ar
    volumes:
      - /etc/localtime:/etc/localtime:ro  # Para syncronizar el clock del contenedor con el del host
      - /etc/timezone:/etc/timezone:ro    # Para syncronizar el clock del contenedor con el del host
